### ISSUE TITLE
ModuleNotFoundError: No module named 'models.posenet'

### ISSUE THREAD

**Issue by 738654805** [crockwell/pytorch_stacked-hourglass-attention#1]
Thank you for sharing your code.
I just follow your suggestion, but when i run the python train -e test, raise the  ModuleNotFoundError: No module named 'models.posenet', i have checked the code, but have no idea about it. I guess if the python version is not suitable，my python version is 3.6.8.
looking forward your help.

**Comment by crockwell** [comment]
Sorry for the late response, I missed this! I don't see this error, so I'm confused as to exactly what is causing it. If it is still a problem, you might want to try re-cloning the code, creating a new conda env, and trying again. Sounds like the directory either doesn't exist or isn't being searched
