### ISSUE TITLE
Is it possible to train the network using hand data sets? To achieve hand posture estimation?

### ISSUE THREAD

**Issue by Wu-Jin-tao** [crockwell/pytorch_stacked-hourglass-attention#2]
Is it possible to train the network using hand data sets?
To achieve hand posture estimation?

**Comment by crockwell** [comment]
For more expressive hand pose estimation I'd recommend a model focused specifically on that. You might find some inspiration from https://fouheylab.eecs.umich.edu/~dandans/projects/100DOH/
